name: Build Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.5
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:"
          pub-cache-key: "flutter-pub:os:-:channel:-:version:-:arch:"
      - run: flutter pub get
      - run: flutter build windows
      - name: copy files
        run: |
          cp C:\Windows\System32\msvcp140.dll build\windows\x64\runner\Release\
          cp C:\Windows\System32\vcruntime140.dll build\windows\x64\runner\Release\
          cp C:\Windows\System32\vcruntime140_1.dll build\windows\x64\runner\Release\

      - name: make installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.5
        with:
          path: setup.iss

      - name: mv dist
        run: mv build\windows\x64\runner\Release\ vrc_avatar_manager-${{ github.ref_name }}

      - name: Create Zip
        uses: thedoctor0/zip-release@b57d897cb5d60cb78b51a507f63fa184cfe35554
        with:
          type: "zip"
          directory: .
          path: vrc_avatar_manager-${{ github.ref_name }}
          filename: vrc_avatar_manager-${{ github.ref_name }}.zip
          exclusions: "*.git*"

      - run: dart run msix:build
      - run: dart run msix:pack

      - name: Make Release
        uses: softprops/action-gh-release@01570a1f39cb168c169c802c3bceb9e93fb10974
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            Output/vrc_avatar_manager-${{ github.ref_name }}.0-installer.exe
            vrc_avatar_manager-${{ github.ref_name }}.zip
            build/windows/x64/runner/Release/vrc_avatar_manager.msix
